tasks:
  - name: run frontend
    openMode: split-left
    init: cd client && npm i --force
    command: npm start

  - name: run backend
    openMode: split-right
    init: cd server && npm i
    command: |
      echo "MongoDB_URL=mongodb://username:password@localhost:27018/" > .env
      npm run dev:docker