---
name: Prettier Lint and Format

on:
  pull_request:
    branches:
      - main

jobs:
  prettier-lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: |
          cd ./server && npm i
          cd ../client && npm i --force

      - name: Run ESLint and Prettier
        run: |
          npm run lint
          npm run format
